### ISSUE TITLE
Adding "By State" argument???

### ISSUE THREAD

**Issue by dwburger** [AnthonyBloomer/rcp#7]
Thanks for sharing this script.  I was just wondering whether there's a way to add an argument to select data for specific states???  I'm specifically interested in the battleground states for the 2020 Presidential election.  Thanks for any guidance you can provide.

**Comment by Nelluk** [comment]
RCP has state-specific pages. I'm pretty sure you could just give it the URL of the state page you are interested in. Such as https://www.realclearpolitics.com/epolls/2020/president/mi/michigan_trump_vs_biden-6761.html

**Comment by dwburger** [comment]
Yes, thanks, I've been able to do that.  Being new to Python, I wasn't sure if I missed the "by-state" argument in the documentation.  I'll work on putting some code together to loop through all the states of interest and see what I get.  I think this is going to be an excellent learning experience for me.

**Comment by AnthonyBloomer** [comment]
Hello @dwburger,

Thank you for creating this issue!

As @Nelluk mentioned, you can pass the URL of the poll to get the polling data for each battleground state, for example:

``` python
from pprint import pprint

from rcp import get_poll_data

battleground_states = [
    "https://www.realclearpolitics.com/epolls/2020/president/wi/wisconsin_trump_vs_biden-6849.html",
    "https://www.realclearpolitics.com/epolls/2020/president/fl/florida_trump_vs_biden-6841.html",
    "https://www.realclearpolitics.com/epolls/2020/president/mi/michigan_trump_vs_biden-6761.html",
    "https://www.realclearpolitics.com/epolls/2020/president/pa/pennsylvania_trump_vs_biden-6861.html",
    "https://www.realclearpolitics.com/epolls/2020/president/nc/north_carolina_trump_vs_biden-6744.html",
    "https://www.realclearpolitics.com/epolls/2020/president/az/arizona_trump_vs_biden-6807.html",
]

for state in battleground_states:
    poll = get_poll_data(state)
    pprint(poll)
```

I have also updated the `get_polls` function with a `state` parameter. So, you could pass the state name and it will search for poll results for that given state. For example, to get the battleground state poll results for Trump:

``` python
from rcp import get_polls

battleground_states = [
    "Wisconsin",
    "Florida",
    "Michigan",
    "Pennsylvania",
    "North Carolina",
    "Arizona",
]

for state in battleground_states:
    polls = get_polls(candidate="Trump", state=state)
    for poll in polls:
        print(poll)
```
I have published this new version to [PyPi](https://pypi.org/project/realclearpolitics/1.4.0/). You can install using pip:

```
pip install realclearpolitics==1.4.0
```
I hope that helps!

**Comment by dwburger** [comment]
Wow...that's terrific help...thanks!  It's exactly what I needed.

**Comment by dwburger** [comment]
I've gotten this to work passing the states in I'm interested and getting the script to pprint the results (e.g. pprint(poll).  However, I'd rather have this output to csv.  I've been working on this, but I've not been successful.  I've been trying to combine the new battleground-states script with the original "output to csv" script.  Would you mind showing me how to get the multiple battleground state data into a csv file?

**Comment by dwburger** [comment]
Just so you know I'm not just a freeloader, I've gotten a method to work that creates the .csv files.  It's probably not the best way, but it gets me where I want to be.  I'm open to critique or any suggestions to improve my skills.  Here's what I've written:

```
#This will take battleground-state polls and create .csv files for each
#The .csv filename will have the state abbreviation as part of its name
#Based on the position of the state's abbreviation in the original URL

import os

battleground_states = [
    "https://www.realclearpolitics.com/epolls/2020/president/wi/wisconsin_trump_vs_biden-6849.html",
    "https://www.realclearpolitics.com/epolls/2020/president/fl/florida_trump_vs_biden-6841.html",
    "https://www.realclearpolitics.com/epolls/2020/president/mi/michigan_trump_vs_biden-6761.html",
    "https://www.realclearpolitics.com/epolls/2020/president/pa/pennsylvania_trump_vs_biden-6861.html",
    "https://www.realclearpolitics.com/epolls/2020/president/nc/north_carolina_trump_vs_biden-6744.html",
    "https://www.realclearpolitics.com/epolls/2020/president/az/arizona_trump_vs_biden-6807.html",
]
for state in battleground_states:
    insert = state[56:58]
    print(state, insert)
    makeCSV = "rcp " + state + " --output " + insert + ".csv"

    os.system (makeCSV)
```

**Comment by AnthonyBloomer** [comment]
Hello @dwburger, nice work! To output as CSV, you can call the API directly rather than using the CLI:

``` python
from rcp import get_poll_data, to_csv

battleground_states = [
    "https://www.realclearpolitics.com/epolls/2020/president/wi/wisconsin_trump_vs_biden-6849.html",
    "https://www.realclearpolitics.com/epolls/2020/president/fl/florida_trump_vs_biden-6841.html",
    "https://www.realclearpolitics.com/epolls/2020/president/mi/michigan_trump_vs_biden-6761.html",
    "https://www.realclearpolitics.com/epolls/2020/president/pa/pennsylvania_trump_vs_biden-6861.html",
    "https://www.realclearpolitics.com/epolls/2020/president/nc/north_carolina_trump_vs_biden-6744.html",
    "https://www.realclearpolitics.com/epolls/2020/president/az/arizona_trump_vs_biden-6807.html",
]

for state in battleground_states:
    insert = state[56:58]
    data = get_poll_data(state, csv_output=True)
    to_csv(filename=insert, poll_data=data)
```

**Comment by dwburger** [comment]
Thanks!  I've struggled seeing how to use the API directly and that will help.

**Comment by dwburger** [comment]
I was under the incorrect notion that your script was accessing an API at RealClearPolitics.com.  I now see that all the data is being obtained with your script(s).  Really impressive!

**Comment by dwburger** [comment]
I've run into an error that I can't seem to solve.  My goal is to create a Python program using your scripts that : 1)asks for the input of battle-ground states, 2) downloads the appropriate polls from RealClearPolitics.com, and 3) processes the polling data resulting in the RCP summaries for each state.  I'm using the original "battleground_states" variable:

```
battleground_states = [
    "Wisconsin",
    "Florida",
    "Michigan",
    "Pennsylvania",
    "North Carolina",
    "Arizona",
]
```
to generate the list of URLs to obtain polling data.  Originally, it looked like this:

```
battleground_states_polls = [
    "https://www.realclearpolitics.com/epolls/2020/president/wi/wisconsin_trump_vs_biden-6849.html",
    "https://www.realclearpolitics.com/epolls/2020/president/fl/florida_trump_vs_biden-6841.html",
    "https://www.realclearpolitics.com/epolls/2020/president/mi/michigan_trump_vs_biden-6761.html",
    "https://www.realclearpolitics.com/epolls/2020/president/pa/pennsylvania_trump_vs_biden-6861.html",
    "https://www.realclearpolitics.com/epolls/2020/president/nc/north_carolina_trump_vs_biden-6744.html",
    "https://www.realclearpolitics.com/epolls/2020/president/az/arizona_trump_vs_biden-6807.html",
]
```
Using this code (I had to change the name to "battleground_states_polls"):

```
pollZero=''
battleground_states_polls = '['

for state in battleground_states:
    polls = get_polls(candidate="Biden", state=state)
    for poll in polls:
        if poll['url'] != pollZero:
            print(poll['url'])
            battleground_states_polls = battleground_states_polls + '"' + poll['url'] + '"' + ','
            pollZero=poll['url']

battleground_states_polls = battleground_states_polls + ']'
print(battleground_states_polls)
```
I obtain this:

battleground_states_polls = 
`["https://www.realclearpolitics.com/epolls/2020/president/wi/wisconsin_trump_vs_biden-6849.html", "https://www.realclearpolitics.com/epolls/2020/president/fl/florida_trump_vs_biden-6841.html", "https://www.realclearpolitics.com/epolls/2020/president/mi/michigan_trump_vs_biden-6761.html", "https://www.realclearpolitics.com/epolls/2020/president/pa/pennsylvania_trump_vs_biden-6861.html", "https://www.realclearpolitics.com/epolls/2020/president/nc/north_carolina_trump_vs_biden-6744.html", "https://www.realclearpolitics.com/epolls/2020/president/az/arizona_trump_vs_biden-6807.html",]
`
This looks just like the object that it replaced.  However, when I run this code:

```
for state in battleground_states_polls:
	insert=state[56:58]
	data=get_poll_data(state, csv_output=True)
	to_csv(filename=insert + ".csv", poll_data=data)  <-- this is line 50
```

I get this error:

```
  File "c:/Users/dwbur/RCP4.py", line 50, in <module>
    to_csv(filename=insert + ".csv", poll_data=data)
  File "C:\Users\dwbur\AppData\Local\Programs\Python\Python38-32\lib\site-packages\rcp\rcp.py", line 106, in to_csv
    writer.writerows(poll_data)
TypeError: writerows() argument must be iterable
```

Python doesn't like line 50 and I'm not able to understand what's going on in line 106 of rcp.py

I hope I've explained the situation clearly enough.  Here is all the code in one place.  Maybe you can tell me what is wrong???

```
from rcp import get_poll_data, to_csv
from rcp import get_polls
import csv

#Determine what battleground states are to be included
#The ones below are included in the script
#Eventually, I'll include additional code to determine that in real time

''' battleground_states_polls= ["https://www.realclearpolitics.com/epolls/2020/president/wi/wisconsin_trump_vs_biden-6849.html","https://www.realclearpolitics.com/epolls/2020/president/fl/florida_trump_vs_biden-6841.html","https://www.realclearpolitics.com/epolls/2020/president/mi/michigan_trump_vs_biden-6761.html","https://www.realclearpolitics.com/epolls/2020/president/pa/pennsylvania_trump_vs_biden-6861.html","https://www.realclearpolitics.com/epolls/2020/president/nc/north_carolina_trump_vs_biden-6744.html","https://www.realclearpolitics.com/epolls/2020/president/az/arizona_trump_vs_biden-6807.html",]
 '''

#This code takes the given battleground states and creates an object (battleground_states_polls)
#that will be used to create .csv files of the poll data
battleground_states = [
    "Wisconsin",
    "Florida",
    "Michigan",
    "Pennsylvania",
    "North Carolina",
    "Arizona",
]

#Create the URL for each battleground state

pollZero=''
battleground_states_polls = '['

for state in battleground_states:
    polls = get_polls(candidate="Biden", state=state)
    for poll in polls:
        if poll['url'] != pollZero:
            print(poll['url'])
            battleground_states_polls = battleground_states_polls + '"' + poll['url'] + '"' + ','
            pollZero=poll['url']

battleground_states_polls = battleground_states_polls + ']'
print(battleground_states_polls)

#This code creates the .csv file for each battleground state
#The name of the .csv file depends on characters 56-58 in the URL that houses the data
#The character position may change with different URLs???

for state in battleground_states_polls:
	insert=state[56:58]
	data=get_poll_data(state, csv_output=True)
	to_csv(filename=insert + ".csv", poll_data=data)


#This section reads the poll data coming from RealClearPolitics.com and
#only writes the averages RCP calculates for each state

input_file = csv.DictReader(open("az.csv"))
for row in input_file:
    if row['Poll'] == 'RCP Average':
        print (row)
        with open('PollSummary.csv', 'r+') as f:
            header = next(csv.reader(f))
            dict_writer = csv.DictWriter(f, header)
            dict_writer.writerow(row)
    else:
        pass

```
So...I can't see why this code works while using this object:

`'battleground_states_polls= ["https://www.realclearpolitics.com/epolls/2020/president/wi/wisconsin_trump_vs_biden-6849.html", "https://www.realclearpolitics.com/epolls/2020/president/fl/florida_trump_vs_biden-6841.html", "https://www.realclearpolitics.com/epolls/2020/president/mi/michigan_trump_vs_biden-6761.html"," https://www.realclearpolitics.com/epolls/2020/president/pa/pennsylvania_trump_vs_biden-6861.html"," https://www.realclearpolitics.com/epolls/2020/president/nc/north_carolina_trump_vs_biden-6744.html"," https://www.realclearpolitics.com/epolls/2020/president/az/arizona_trump_vs_biden-6807.html",]
 `

but not this one:

`battleground_states_polls= ["https://www.realclearpolitics.com/epolls/2020/president/wi/wisconsin_trump_vs_biden-6849.html", "https://www.realclearpolitics.com/epolls/2020/president/fl/florida_trump_vs_biden-6841.html", "https://www.realclearpolitics.com/epolls/2020/president/mi/michigan_trump_vs_biden-6761.html", "https://www.realclearpolitics.com/epolls/2020/president/pa/pennsylvania_trump_vs_biden-6861.html", "https://www.realclearpolitics.com/epolls/2020/president/nc/north_carolina_trump_vs_biden-6744.html", "https://www.realclearpolitics.com/epolls/2020/president/az/arizona_trump_vs_biden-6807.html",]`


Thanks for any suggestions you can provide!

**Comment by dwburger** [comment]
This is the entire terminal output when the above code is processed:

```
https://www.realclearpolitics.com/epolls/2020/president/wi/wisconsin_trump_vs_biden-6849.html
https://www.realclearpolitics.com/epolls/2020/president/fl/florida_trump_vs_biden-6841.html
https://www.realclearpolitics.com/epolls/2020/president/mi/michigan_trump_vs_biden-6761.html
https://www.realclearpolitics.com/epolls/2020/president/pa/pennsylvania_trump_vs_biden-6861.html
https://www.realclearpolitics.com/epolls/2020/president/nc/north_carolina_trump_vs_biden-6744.html
https://www.realclearpolitics.com/epolls/2020/president/az/arizona_trump_vs_biden-6807.html
["https://www.realclearpolitics.com/epolls/2020/president/wi/wisconsin_trump_vs_biden-6849.html","https://www.realclearpolitics.com/epolls/2020/president/fl/florida_trump_vs_biden-6841.html","https://www.realclearpolitics.com/epolls/2020/president/mi/michigan_trump_vs_biden-6761.html","https://www.realclearpolitics.com/epolls/2020/president/pa/pennsylvania_trump_vs_biden-6861.html","https://www.realclearpolitics.com/epolls/2020/president/nc/north_carolina_trump_vs_biden-6744.html","https://www.realclearpolitics.com/epolls/2020/president/az/arizona_trump_vs_biden-6807.html",]
Traceback (most recent call last):
  File "c:/Users/dwbur/RCP4.py", line 52, in <module>
    to_csv(filename=insert + ".csv", poll_data=data)
  File "C:\Users\dwbur\AppData\Local\Programs\Python\Python38-32\lib\site-packages\rcp\rcp.py", line 106, in to_csv
    writer.writerows(poll_data)
TypeError: writerows() argument must be iterable
```

**Comment by AnthonyBloomer** [comment]
Hello @dwburger, I noticed you are building a string, not an array:

``` python
battleground_states_polls = battleground_states_polls + '"' + poll['url'] + '"' + ','
```

 So when you try to iterate over `battleground_states_polls` the loop will iterate over each character. 

You could set `battleground_states_polls` as an empty list then append the urls to that:

``` python
battleground_states_polls = []
for state in battleground_states:
    polls = get_polls(candidate="Biden", state=state)
    for poll in polls:
        if poll['url'] != pollZero:
            print(poll['url'])
            battleground_states_polls.append(poll['url'])
            pollZero = poll['url']

```
