### ISSUE TITLE
Error in get_poll_data function

### ISSUE THREAD

**Issue by rahulpatel033** [AnthonyBloomer/rcp#8]
Thank you for sharing this script.
Found error in `get_poll_data` function.
`p.append([ele.text.strip() for ele in cols])`
This line gets the texts for each cell of the table. The problem is for column **Poll**, the website has hidden element for mobile view with the same text so it returns text twice or append mobile view text.
```
 {
                "Biden (D)": "46",
                "Sample": "1099 RV",
                "Spread": "Tie",
                "MoE": "3.8",
                "Date": "7/7 - 7/10",
                "Poll": "CBS News/YouGovCBS News",
                "Trump (R)": "46"
            }
```
The poll value should be "**CBS News/YouGov**".

**Comment by AnthonyBloomer** [comment]
Hello @rahulpatel033, thank you for reporting this issue! 👍 I've pushed a fix there that checks if `normal_pollster_name` exists then only append that elements text, otherwise append the whole column text:

``` python
 for row in rows:
        cols = row.find_all(["th", "td"])
        tmp = []
        for ele in cols:
            if ele.find("a", {"class": "normal_pollster_name"}):
                tmp.append(
                    ele.find("a", {"class": "normal_pollster_name"}).text.strip()
                )
            else:
                tmp.append(ele.text.strip())
        p.append(tmp)
```
